# Generated by Django 5.2.6 on 2025-10-02 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_realise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('indicateur', models.CharField(blank=True, max_length=250)),
                ('etat', models.CharField(default='En cours', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CadreLogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif_general', models.TextField(blank=True)),
                ('resultat_attendu', models.TextField(blank=True)),
                ('activite_associee', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCOPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superviseur', 'Superviseur')], default='user', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivitePTA',
        ),
        migrations.AddField(
            model_name='activite',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.service'),
        ),
    ]
