# Generated by Django 5.2.6 on 2025-10-07 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activite_cadrelogique_pcopentry_service_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='description',
            new_name='activite',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='responsable',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='budget_prevu',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='budget_realise',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='indicateur',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='intitule',
        ),
        migrations.RemoveField(
            model_name='pcopentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='activite',
            name='cibles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activite',
            name='cout_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='division',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='activite',
            name='libelle_pcop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activite',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='objectif_general',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activite',
            name='objectif_specifique',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activite',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='pcop',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activite',
            name='produits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='resultat_attendu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activite',
            name='sources_financement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activite',
            name='sous_activite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='structure',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cadrelogique',
            name='objectif_specifique',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pcopentry',
            name='libelle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activite',
            name='etat',
            field=models.CharField(blank=True, default='En cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateField()),
                ('observation', models.TextField(blank=True)),
                ('avancement', models.IntegerField(blank=True, null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='api.activite')),
            ],
        ),
    ]
