# Generated by Django 5.2.6 on 2025-10-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_description_activite_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superviseur', 'Superviseur')], default='admin', max_length=20),
        ),
    ]
