# Generated by Django 5.2.6 on 2025-10-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='objectif_general',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='objectif_specifique',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='resultat_attendu',
        ),
        migrations.AddField(
            model_name='activite',
            name='cadre_logique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.cadrelogique', verbose_name='Cadre logique associé'),
        ),
    ]
