# Generated by Django 5.2.6 on 2025-11-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_activite_objectif_general_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Objectif Général',
                'verbose_name_plural': 'Objectifs Généraux',
            },
        ),
        migrations.RemoveField(
            model_name='activite',
            name='cadre_logique',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='libelle_pcop',
        ),
        migrations.AlterField(
            model_name='activite',
            name='pcop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.pcopentry'),
        ),
        migrations.AddField(
            model_name='activite',
            name='objectif_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.objectifgeneral'),
        ),
        migrations.CreateModel(
            name='ObjectifSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objectif_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_specifiques', to='api.objectifgeneral')),
            ],
            options={
                'verbose_name': 'Objectif Spécifique',
                'verbose_name_plural': 'Objectifs Spécifiques',
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='objectif_specifique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.objectifspecifique'),
        ),
        migrations.CreateModel(
            name='ResultatAttendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('objectif_specifique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_attendus', to='api.objectifspecifique')),
            ],
            options={
                'verbose_name': 'Résultat Attendu',
                'verbose_name_plural': 'Résultats Attendus',
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='resultat_attendu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resultatattendu'),
        ),
        migrations.DeleteModel(
            name='CadreLogique',
        ),
    ]
