# Generated by Django 5.2.6 on 2025-11-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_direction_alter_service_options_service_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
        migrations.AlterField(
            model_name='activite',
            name='objectif_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.objectifgeneral'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='objectif_specifique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.objectifspecifique'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='resultat_attendu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.resultatattendu'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='numero',
            field=models.CharField(default='D1', max_length=10),
        ),
        migrations.AlterField(
            model_name='division',
            name='numero',
            field=models.CharField(default='DV1', max_length=10),
        ),
        migrations.AlterField(
            model_name='division',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='api.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='numero',
            field=models.CharField(default='S1', max_length=10),
        ),
        migrations.AddField(
            model_name='direction',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='api.structure'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.structure'),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('structure', 'numero')},
        ),
    ]
