# Generated by Django 5.2.6 on 2025-11-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_structure_alter_activite_objectif_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcopentry',
            old_name='budget',
            new_name='cout_unitaire',
        ),
    ]
