# Generated by Django 5.2.6 on 2025-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_budget_pcopentry_cout_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin prévue'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='message_notification',
            field=models.TextField(blank=True, verbose_name='Message de notification'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='notification_retard',
            field=models.BooleanField(default=False, verbose_name='Notification de retard'),
        ),
    ]
